[2020-05-07 10:17:21,430] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 10:17:34,258] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/ HTTP/1.1" 200 249927
[2020-05-07 10:17:34,340] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/docs/css/base.css HTTP/1.1" 304 0
[2020-05-07 10:17:34,372] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[2020-05-07 10:17:34,372] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/font-awesome-4.0.3.css HTTP/1.1" 304 0
[2020-05-07 10:17:34,373] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/docs/css/jquery.json-view.min.css HTTP/1.1" 304 0
[2020-05-07 10:17:34,373] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-theme.min.css HTTP/1.1" 304 0
[2020-05-07 10:17:34,405] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/coreapi-0.1.1.js HTTP/1.1" 304 0
[2020-05-07 10:17:34,484] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/schema.js HTTP/1.1" 200 37564
[2020-05-07 10:17:34,972] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 304 0
[2020-05-07 10:17:35,106] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-05-07 10:17:35,106] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[2020-05-07 10:17:35,113] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/docs/js/api.js HTTP/1.1" 304 0
[2020-05-07 10:17:35,113] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/docs/js/jquery.json-view.min.js HTTP/1.1" 304 0
[2020-05-07 10:19:48,259] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\settings.py changed, reloading.
[2020-05-07 10:19:49,679] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 10:22:40,606] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\urls.py changed, reloading.
[2020-05-07 10:22:41,692] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 10:23:39,295] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\settings.py changed, reloading.
[2020-05-07 10:23:40,414] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 10:25:08,695] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\settings.py changed, reloading.
[2020-05-07 10:25:09,728] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 10:26:17,664] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/ HTTP/1.1" 200 258935
[2020-05-07 10:26:17,761] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/schema.js HTTP/1.1" 200 37564
[2020-05-07 10:26:17,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 14984
[2020-05-07 10:26:17,838] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404
[2020-05-07 10:26:17,845] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 12791
[2020-05-07 10:26:17,906] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41
[2020-05-07 10:26:18,030] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/docs/img/favicon.ico HTTP/1.1" 200 5430
[2020-05-07 10:26:28,616] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 10:26:51,724] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 63
[2020-05-07 10:27:07,500] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/ HTTP/1.1" 200 258935
[2020-05-07 10:27:07,574] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/schema.js HTTP/1.1" 200 37564
[2020-05-07 10:27:07,745] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/docs/img/favicon.ico HTTP/1.1" 200 5430
[2020-05-07 10:27:15,618] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 63
[2020-05-07 10:45:01,449] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\urls.py changed, reloading.
[2020-05-07 10:45:02,885] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 10:47:36,769] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /docs/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\middleware.py", line 99, in __call__
    bits[-2] += toolbar.render_toolbar()
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\toolbar.py", line 69, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\cnas\server\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\test\utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
[2020-05-07 10:47:36,774] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /docs/ HTTP/1.1" 500 142680
[2020-05-07 10:47:37,110] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\middleware.py", line 99, in __call__
    bits[-2] += toolbar.render_toolbar()
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\toolbar.py", line 69, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\cnas\server\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\test\utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
[2020-05-07 10:47:37,113] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 139928
[2020-05-07 10:47:44,899] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /docs/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\middleware.py", line 99, in __call__
    bits[-2] += toolbar.render_toolbar()
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\toolbar.py", line 69, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\cnas\server\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\test\utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
[2020-05-07 10:47:44,902] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /docs/ HTTP/1.1" 500 142536
[2020-05-07 10:47:45,137] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\middleware.py", line 99, in __call__
    bits[-2] += toolbar.render_toolbar()
  File "E:\cnas\server\venv\lib\site-packages\debug_toolbar\toolbar.py", line 69, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\cnas\server\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\test\utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "E:\cnas\server\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\cnas\server\venv\lib\site-packages\django\urls\base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
[2020-05-07 10:47:45,143] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 139663
[2020-05-07 10:47:57,498] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\settings.py changed, reloading.
[2020-05-07 10:47:58,603] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 10:48:00,565] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/ HTTP/1.1" 200 249927
[2020-05-07 10:48:00,639] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /docs/schema.js HTTP/1.1" 200 37564
[2020-05-07 10:48:00,895] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/docs/img/favicon.ico HTTP/1.1" 200 5430
[2020-05-07 11:30:16,945] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:30:16,955] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /rbac/user/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\cnas\server\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: name__contains
[2020-05-07 11:30:16,960] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 500 19913
[2020-05-07 11:30:16,967] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 11:33:45,696] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\views.py changed, reloading.
[2020-05-07 11:33:47,041] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 11:34:01,958] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 11:34:02,378] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:34:02,388] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /rbac/user/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\cnas\server\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: name__contains
[2020-05-07 11:34:02,393] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 500 19913
[2020-05-07 11:34:02,511] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 11:35:36,873] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 11:35:37,134] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:35:37,213] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /rbac/user/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\cnas\server\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: name__contains
[2020-05-07 11:35:37,223] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 500 19913
[2020-05-07 11:35:37,260] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 11:37:41,301] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 11:37:45,440] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 11:37:45,842] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:37:45,853] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /rbac/user/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\cnas\server\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: name__contains
[2020-05-07 11:37:45,862] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 500 19913
[2020-05-07 11:37:45,975] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 11:38:16,234] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 11:38:18,565] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 11:38:18,962] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:38:18,971] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /rbac/user/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\cnas\server\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: name__contains
[2020-05-07 11:38:18,978] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 500 19913
[2020-05-07 11:38:19,093] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 11:39:16,340] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 11:39:16,618] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:39:16,747] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 11:39:16,940] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /rbac/user/
Traceback (most recent call last):
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\cnas\server\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\cnas\server\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "E:\cnas\server\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "E:\cnas\server\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "E:\cnas\server\venv\lib\site-packages\django_filters\filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: name__contains
[2020-05-07 11:39:16,948] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 500 19913
[2020-05-07 11:49:01,457] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\views.py changed, reloading.
[2020-05-07 11:49:02,522] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 11:51:25,240] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\views.py changed, reloading.
[2020-05-07 11:51:26,389] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 11:51:31,223] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 11:51:31,572] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:51:31,671] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 200 427
[2020-05-07 11:51:31,700] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 11:51:46,686] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/user/?page=1&page_size=20&name=%E5%BC%A0 HTTP/1.1" 200 0
[2020-05-07 11:51:46,832] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&name=%E5%BC%A0 HTTP/1.1" 200 427
[2020-05-07 11:53:14,170] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\filters.py changed, reloading.
[2020-05-07 11:53:15,172] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 11:53:20,440] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\filters.py changed, reloading.
[2020-05-07 11:53:21,520] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 11:53:25,601] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&name=%E5%BC%A0 HTTP/1.1" 200 83
[2020-05-07 11:53:37,054] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/user/?page=1&page_size=20&name=a HTTP/1.1" 200 0
[2020-05-07 11:53:37,166] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&name=a HTTP/1.1" 200 83
[2020-05-07 11:53:42,281] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 11:53:42,680] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 200 427
[2020-05-07 11:53:42,791] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 11:53:42,872] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 15:05:40,546] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\views.py changed, reloading.
[2020-05-07 15:05:43,150] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 15:05:46,219] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\views.py changed, reloading.
[2020-05-07 15:05:47,215] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 15:08:00,271] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\settings.py changed, reloading.
[2020-05-07 15:08:01,318] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 15:08:34,020] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\views.py changed, reloading.
[2020-05-07 15:08:35,045] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 16:44:07,133] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\settings.py changed, reloading.
[2020-05-07 16:44:08,568] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 16:44:12,684] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\server\settings.py changed, reloading.
[2020-05-07 16:44:13,824] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 17:22:43,122] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\models.py changed, reloading.
[2020-05-07 17:22:44,649] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 17:53:34,183] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/user/info/ HTTP/1.1" 200 0
[2020-05-07 17:53:34,954] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 17:53:35,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/user/?page=1&page_size=20 HTTP/1.1" 200 0
[2020-05-07 17:53:35,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/organization/ HTTP/1.1" 200 0
[2020-05-07 17:53:35,114] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/role/ HTTP/1.1" 200 0
[2020-05-07 17:53:36,281] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 17:53:36,296] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 200 427
[2020-05-07 17:53:36,301] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 17:53:43,328] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 17:53:44,610] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/permission/ HTTP/1.1" 200 0
[2020-05-07 17:53:44,742] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 17:53:44,742] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 17:53:44,742] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/permission/ HTTP/1.1" 200 422
[2020-05-07 17:54:41,350] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 17:54:41,357] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 17:54:41,394] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 200 427
[2020-05-07 17:55:08,390] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\views.py changed, reloading.
[2020-05-07 17:55:09,669] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 17:55:13,445] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/user/?page=1&page_size=20&is_active=true HTTP/1.1" 200 0
[2020-05-07 17:55:13,679] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&is_active=true HTTP/1.1" 200 427
[2020-05-07 17:55:14,676] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/user/?page=1&page_size=20&is_active= HTTP/1.1" 200 0
[2020-05-07 17:55:14,807] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&is_active= HTTP/1.1" 200 427
[2020-05-07 17:55:16,405] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /rbac/user/?page=1&page_size=20&is_active=false HTTP/1.1" 200 0
[2020-05-07 17:55:16,554] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&is_active=false HTTP/1.1" 200 427
[2020-05-07 17:55:17,875] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&is_active= HTTP/1.1" 200 427
[2020-05-07 17:55:35,332] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\django-vue-rbac\server\apps\rbac\filters.py changed, reloading.
[2020-05-07 17:55:36,365] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-07 17:55:40,281] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/info/ HTTP/1.1" 200 136
[2020-05-07 17:55:40,701] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/organization/ HTTP/1.1" 200 798
[2020-05-07 17:55:40,722] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20 HTTP/1.1" 200 427
[2020-05-07 17:55:40,818] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
[2020-05-07 17:55:44,487] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&is_active=false HTTP/1.1" 200 83
[2020-05-07 17:55:47,702] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/user/?page=1&page_size=20&is_active= HTTP/1.1" 200 427
[2020-05-07 17:56:40,846] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 63
[2020-05-07 17:57:01,279] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /token/ HTTP/1.1" 200 469
[2020-05-07 17:57:43,961] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /rbac/role/ HTTP/1.1" 200 217
